import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import whatsappImg from "../public/assets/whatsapp-home.png";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Whatsapp 2.0 Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Image src={whatsappImg} alt="Whatsapp Logo" height={250} width={250} />
        <h2 style={{ color: "#727372" }}>Keep your phone connected.</h2>
        <p style={{ color: "#b7b9bb" }}>
          WhatsApp connects to your phone to sync messages. To reduce data
          usage, connect your phone to Wi-Fi.
        </p>
      </Section>
    </Container>
  );
}

const Container = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #f8fafc;
  height: 100%;
  width: 100%;
`;

const Section = styled.div`
  width: 50%;
  text-align: center;
`;
