import Head from "next/head";
import Image from "next/image";
import whatsappImg from "../public/assets/whatsapp-home.png";

export default function Home() {
  return (
    <div className="flex items-center justify-center bg-[#f8fafc] h-full w-full">
      <Head>
        <title>Whatsapp 2.0 Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-1/2 text-center">
        <Image src={whatsappImg} alt="Whatsapp Logo" height={250} width={250} />
        <h2 className=" text-[#727372]">Keep your phone connected.</h2>
        <p className="text-[#b7b9bb]">
          WhatsApp connects to your phone to sync messages. To reduce data
          usage, connect your phone to Wi-Fi.
        </p>
      </div>
    </div>
  );
}
